### ISSUE TITLE
No devices or entities

### ISSUE THREAD

**Issue by brietman** [DominikWrobel/viomise#2]
Can't add my Viomi SE.

I add my vacuum, but I get: No devices or entities. I restarted my HA system, but still no luck. 

```
2024-10-09 16:57:52.379 ERROR (MainThread) [homeassistant.components.vacuum] viomise: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 724, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/viomise/vacuum.py", line 474, in update
    self.vacuum_state[prop] = self.vacuum_state[VACUUM_CARD_PROPS_REFERENCES[prop]]
```

After I reload the integration
```
2024-10-09 17:04:30.139 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Rosey for viomise
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 809, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/viomise/__init__.py", line 20, in async_unload_entry
    hass.data[DOMAIN].pop(entry.entry_id)
KeyError: '01J9RVTGZE84RG89HW26BXG626'
```

**Comment by DominikWrobel** [comment]
Please provide your vacuum model, HA version and integration version.

**Comment by brietman** [comment]
Core 2024.10.1
Supervisor 2024.10.0
Operating System 13.1
Frontend 20241002.2

 Viomi SE with 4.0.9_0017 firmware 
Looking at the get mi home token app: viomi.vacuum.v19 / V-RVCLM21A 

Integration version: V1.3

Looking deeper on your github. I see that you mention Viomi SE and that you call your integration "Viomi SE", but it's not listed as supported. The V-RVCLM21B is the Viomi V2 (which is almost the same version, but  SE is based on the V3).
To be clear I have the vacuum that's supported by https://github.com/marotoweb/home-assistant-vacuum-viomise. Which is a fork of https://github.com/KrzysztofHajdamowicz/home-assistant-vacuum-styj02ym

**Comment by DominikWrobel** [comment]
OK, try the v1.3-beta, but first remove the integration and after downloading of beta version add the vacuum again. This should fix the problem your having. If everything works ok I will move this to a regular release.

**Comment by brietman** [comment]
Thank you. I did. Now I can add my vacuum, but it can't connect. It says: This entity is no longer available from the viomise integration. When the entity is no longer in use, it can be deleted from the settings.

Logs:
```
2024-10-10 10:49:50.687 ERROR (MainThread) [homeassistant.components.vacuum] Error adding entity vacuum.rosey for domain vacuum with platform viomise
Traceback (most recent call last):
  File "/config/custom_components/viomise/vacuum.py", line 297, in state
    return STATE_CODE_TO_STATE[int(self.vacuum_state['run_state'])]
                                   ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'run_state'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 909, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1366, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1011, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/viomise/vacuum.py", line 301, in state
    self.vacuum_state['run_state'],
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'run_state'
```

**Comment by DominikWrobel** [comment]
I took a closer look at the integration by @marotoweb and it does not support my vacuum, but the changes made suggest it support your model. Now as I am not a developer there is little I can do without substantial help from others to get this integration to work with more types of vacuums. I think you should stick with this integration:

https://github.com/marotoweb/home-assistant-vacuum-viomise/

and update the minifest.json located in custom_components/viomise folder to this:

```
{
  "domain": "viomise",
  "name": "Viomi Robot Vacuum Cleaner SE (V-RVCLM21A)",
  "documentation": "https://github.com/marotoweb/home-assistant-vacuum-viomise",
  "issue_tracker": "https://github.com/marotoweb/home-assistant-vacuum-viomise/issues",
  "requirements": ["construct==2.10.70", "python-miio>=0.5.12"],
  "dependencies": [],
  "codeowners": ["@nqkdev", "@KrzysztofHajdamowicz", "@marotoweb"],
  "config_flow": false,
  "iot_class": "local_polling",
  "version": "v2021.05.16"
}
```

This updates the requirements to the ones working with HA, and should get the integration to work with HA 2024.10+

**Comment by brietman** [comment]
I see. Tank you, I will look at this soon and make a pull request or a fork.

But did you name your fork Viomi SE because of the Viomi SE model or for some other reason? I think you comment https://github.com/marotoweb/home-assistant-vacuum-viomise/issues/27#issuecomment-2389790246 caused confusion with me, maybe change it?

I am not a big coder, but if marotoweb version is a fork of the version your version is a fork off, can't we merged it?

**Comment by DominikWrobel** [comment]
The name Viomi SE is what my device tag says, so I just used it, my model is V-RVCLM21B but when I bought it, it came with the Viomi APP software, but the store agreed to upgrade the software to Xiaomi for free.

The fork seems to have a different protocol for communication with the vacuum but the commands are the same, if I have some free time I will try to marge the two protocols into one version. I think the @marotoweb integration should work until january and I will try to have my new version with both protocols before that.

I will close this issue for now.
